# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/design_1_v_proc_ss_2_1.xci
# IP: The module: 'design_1_v_proc_ss_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/bd_d94b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b || ORIG_REF_NAME==bd_d94b} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_0/bd_d94b_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_smartconnect_0_0 || ORIG_REF_NAME==bd_d94b_smartconnect_0_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_1/bd_d94b_vsc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_vsc_0 || ORIG_REF_NAME==bd_d94b_vsc_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_2/bd_d94b_hsc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_hsc_0 || ORIG_REF_NAME==bd_d94b_hsc_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_3/bd_d94b_input_size_set_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_input_size_set_0 || ORIG_REF_NAME==bd_d94b_input_size_set_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_4/bd_d94b_ltr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_ltr_0 || ORIG_REF_NAME==bd_d94b_ltr_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_5/bd_d94b_csc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_csc_0 || ORIG_REF_NAME==bd_d94b_csc_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_6/bd_d94b_proc_ss_ip_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_proc_ss_ip_aresetn_0 || ORIG_REF_NAME==bd_d94b_proc_ss_ip_aresetn_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_7/bd_d94b_vid_in_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_vid_in_aresetn_0 || ORIG_REF_NAME==bd_d94b_vid_in_aresetn_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_9/bd_d94b_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_xbar_0 || ORIG_REF_NAME==bd_d94b_xbar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_8/bd_d94b_video_router_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_video_router_0 || ORIG_REF_NAME==bd_d94b_video_router_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_10/bd_d94b_reset_sel_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_reset_sel_axis_0 || ORIG_REF_NAME==bd_d94b_reset_sel_axis_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_11/bd_d94b_rst_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_rst_axis_0 || ORIG_REF_NAME==bd_d94b_rst_axis_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_24/bd_d94b_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_0 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_25/bd_d94b_auto_ss_slid_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_1 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_1} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_26/bd_d94b_auto_ss_slid_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_2 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_2} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_27/bd_d94b_auto_ss_slid_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_3 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_3} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_28/bd_d94b_auto_ss_slid_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_4 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_4} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_12/bd_d94b_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m00_regslice_0 || ORIG_REF_NAME==bd_d94b_m00_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_13/bd_d94b_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m01_regslice_0 || ORIG_REF_NAME==bd_d94b_m01_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_20/bd_d94b_auto_ss_slidr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_0 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_14/bd_d94b_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m02_regslice_0 || ORIG_REF_NAME==bd_d94b_m02_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_21/bd_d94b_auto_ss_slidr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_1 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_1} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_15/bd_d94b_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m04_regslice_0 || ORIG_REF_NAME==bd_d94b_m04_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_22/bd_d94b_auto_ss_slidr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_2 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_2} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_16/bd_d94b_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m05_regslice_0 || ORIG_REF_NAME==bd_d94b_m05_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_17/bd_d94b_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m06_regslice_0 || ORIG_REF_NAME==bd_d94b_m06_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_18/bd_d94b_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m07_regslice_0 || ORIG_REF_NAME==bd_d94b_m07_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_19/bd_d94b_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m08_regslice_0 || ORIG_REF_NAME==bd_d94b_m08_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_23/bd_d94b_auto_ss_slidr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_3 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_3} -quiet] -quiet

# XDC: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/bd_d94b_ooc.xdc

# XDC: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/design_1_v_proc_ss_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_2_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/design_1_v_proc_ss_2_1.xci
# IP: The module: 'design_1_v_proc_ss_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/bd_d94b.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b || ORIG_REF_NAME==bd_d94b} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_0/bd_d94b_smartconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_smartconnect_0_0 || ORIG_REF_NAME==bd_d94b_smartconnect_0_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_1/bd_d94b_vsc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_vsc_0 || ORIG_REF_NAME==bd_d94b_vsc_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_2/bd_d94b_hsc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_hsc_0 || ORIG_REF_NAME==bd_d94b_hsc_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_3/bd_d94b_input_size_set_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_input_size_set_0 || ORIG_REF_NAME==bd_d94b_input_size_set_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_4/bd_d94b_ltr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_ltr_0 || ORIG_REF_NAME==bd_d94b_ltr_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_5/bd_d94b_csc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_csc_0 || ORIG_REF_NAME==bd_d94b_csc_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_6/bd_d94b_proc_ss_ip_aresetn_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_proc_ss_ip_aresetn_0 || ORIG_REF_NAME==bd_d94b_proc_ss_ip_aresetn_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_7/bd_d94b_vid_in_aresetn_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_vid_in_aresetn_0 || ORIG_REF_NAME==bd_d94b_vid_in_aresetn_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_9/bd_d94b_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_xbar_0 || ORIG_REF_NAME==bd_d94b_xbar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_8/bd_d94b_video_router_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_video_router_0 || ORIG_REF_NAME==bd_d94b_video_router_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_10/bd_d94b_reset_sel_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_reset_sel_axis_0 || ORIG_REF_NAME==bd_d94b_reset_sel_axis_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_11/bd_d94b_rst_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_rst_axis_0 || ORIG_REF_NAME==bd_d94b_rst_axis_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_24/bd_d94b_auto_ss_slid_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_0 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_25/bd_d94b_auto_ss_slid_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_1 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_1} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_26/bd_d94b_auto_ss_slid_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_2 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_2} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_27/bd_d94b_auto_ss_slid_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_3 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_3} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_28/bd_d94b_auto_ss_slid_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slid_4 || ORIG_REF_NAME==bd_d94b_auto_ss_slid_4} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_12/bd_d94b_m00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m00_regslice_0 || ORIG_REF_NAME==bd_d94b_m00_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_13/bd_d94b_m01_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m01_regslice_0 || ORIG_REF_NAME==bd_d94b_m01_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_20/bd_d94b_auto_ss_slidr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_0 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_14/bd_d94b_m02_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m02_regslice_0 || ORIG_REF_NAME==bd_d94b_m02_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_21/bd_d94b_auto_ss_slidr_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_1 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_1} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_15/bd_d94b_m04_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m04_regslice_0 || ORIG_REF_NAME==bd_d94b_m04_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_22/bd_d94b_auto_ss_slidr_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_2 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_2} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_16/bd_d94b_m05_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m05_regslice_0 || ORIG_REF_NAME==bd_d94b_m05_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_17/bd_d94b_m06_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m06_regslice_0 || ORIG_REF_NAME==bd_d94b_m06_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_18/bd_d94b_m07_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m07_regslice_0 || ORIG_REF_NAME==bd_d94b_m07_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_19/bd_d94b_m08_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_m08_regslice_0 || ORIG_REF_NAME==bd_d94b_m08_regslice_0} -quiet] -quiet

# IP: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/ip/ip_23/bd_d94b_auto_ss_slidr_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d94b_auto_ss_slidr_3 || ORIG_REF_NAME==bd_d94b_auto_ss_slidr_3} -quiet] -quiet

# XDC: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/bd_0/bd_d94b_ooc.xdc

# XDC: c:/Users/jaxie963/Temp/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_2_1/design_1_v_proc_ss_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
