# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/design_1_v_proc_ss_1_0.xci
# IP: The module: 'design_1_v_proc_ss_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/bd_197a.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a || ORIG_REF_NAME==bd_197a} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_0/bd_197a_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_smartconnect_0_0 || ORIG_REF_NAME==bd_197a_smartconnect_0_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_1/bd_197a_vsc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_vsc_0 || ORIG_REF_NAME==bd_197a_vsc_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_2/bd_197a_hsc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_hsc_0 || ORIG_REF_NAME==bd_197a_hsc_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_3/bd_197a_input_size_set_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_input_size_set_0 || ORIG_REF_NAME==bd_197a_input_size_set_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_4/bd_197a_ltr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_ltr_0 || ORIG_REF_NAME==bd_197a_ltr_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_5/bd_197a_csc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_csc_0 || ORIG_REF_NAME==bd_197a_csc_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_6/bd_197a_proc_ss_ip_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_proc_ss_ip_aresetn_0 || ORIG_REF_NAME==bd_197a_proc_ss_ip_aresetn_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_7/bd_197a_vid_in_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_vid_in_aresetn_0 || ORIG_REF_NAME==bd_197a_vid_in_aresetn_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_9/bd_197a_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_xbar_0 || ORIG_REF_NAME==bd_197a_xbar_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_8/bd_197a_video_router_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_video_router_0 || ORIG_REF_NAME==bd_197a_video_router_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_10/bd_197a_reset_sel_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_reset_sel_axis_0 || ORIG_REF_NAME==bd_197a_reset_sel_axis_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_11/bd_197a_rst_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_rst_axis_0 || ORIG_REF_NAME==bd_197a_rst_axis_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_12/bd_197a_hcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_hcr_0 || ORIG_REF_NAME==bd_197a_hcr_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_26/bd_197a_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_0 || ORIG_REF_NAME==bd_197a_auto_ss_slid_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_27/bd_197a_auto_ss_slid_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_1 || ORIG_REF_NAME==bd_197a_auto_ss_slid_1} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_28/bd_197a_auto_ss_slid_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_2 || ORIG_REF_NAME==bd_197a_auto_ss_slid_2} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_29/bd_197a_auto_ss_slid_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_3 || ORIG_REF_NAME==bd_197a_auto_ss_slid_3} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_30/bd_197a_auto_ss_slid_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_4 || ORIG_REF_NAME==bd_197a_auto_ss_slid_4} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_31/bd_197a_auto_ss_slid_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_5 || ORIG_REF_NAME==bd_197a_auto_ss_slid_5} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_13/bd_197a_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m00_regslice_0 || ORIG_REF_NAME==bd_197a_m00_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_14/bd_197a_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m01_regslice_0 || ORIG_REF_NAME==bd_197a_m01_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_21/bd_197a_auto_ss_slidr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_0 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_15/bd_197a_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m02_regslice_0 || ORIG_REF_NAME==bd_197a_m02_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_22/bd_197a_auto_ss_slidr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_1 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_1} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_16/bd_197a_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m04_regslice_0 || ORIG_REF_NAME==bd_197a_m04_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_23/bd_197a_auto_ss_slidr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_2 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_2} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_17/bd_197a_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m05_regslice_0 || ORIG_REF_NAME==bd_197a_m05_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_24/bd_197a_auto_ss_slidr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_3 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_3} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_18/bd_197a_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m06_regslice_0 || ORIG_REF_NAME==bd_197a_m06_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_19/bd_197a_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m07_regslice_0 || ORIG_REF_NAME==bd_197a_m07_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_20/bd_197a_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m08_regslice_0 || ORIG_REF_NAME==bd_197a_m08_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_25/bd_197a_auto_ss_slidr_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_4 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_4} -quiet] -quiet

# XDC: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/bd_197a_ooc.xdc

# XDC: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/design_1_v_proc_ss_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/design_1_v_proc_ss_1_0.xci
# IP: The module: 'design_1_v_proc_ss_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/bd_197a.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a || ORIG_REF_NAME==bd_197a} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_0/bd_197a_smartconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_smartconnect_0_0 || ORIG_REF_NAME==bd_197a_smartconnect_0_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_1/bd_197a_vsc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_vsc_0 || ORIG_REF_NAME==bd_197a_vsc_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_2/bd_197a_hsc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_hsc_0 || ORIG_REF_NAME==bd_197a_hsc_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_3/bd_197a_input_size_set_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_input_size_set_0 || ORIG_REF_NAME==bd_197a_input_size_set_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_4/bd_197a_ltr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_ltr_0 || ORIG_REF_NAME==bd_197a_ltr_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_5/bd_197a_csc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_csc_0 || ORIG_REF_NAME==bd_197a_csc_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_6/bd_197a_proc_ss_ip_aresetn_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_proc_ss_ip_aresetn_0 || ORIG_REF_NAME==bd_197a_proc_ss_ip_aresetn_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_7/bd_197a_vid_in_aresetn_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_vid_in_aresetn_0 || ORIG_REF_NAME==bd_197a_vid_in_aresetn_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_9/bd_197a_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_xbar_0 || ORIG_REF_NAME==bd_197a_xbar_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_8/bd_197a_video_router_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_video_router_0 || ORIG_REF_NAME==bd_197a_video_router_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_10/bd_197a_reset_sel_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_reset_sel_axis_0 || ORIG_REF_NAME==bd_197a_reset_sel_axis_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_11/bd_197a_rst_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_rst_axis_0 || ORIG_REF_NAME==bd_197a_rst_axis_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_12/bd_197a_hcr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_hcr_0 || ORIG_REF_NAME==bd_197a_hcr_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_26/bd_197a_auto_ss_slid_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_0 || ORIG_REF_NAME==bd_197a_auto_ss_slid_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_27/bd_197a_auto_ss_slid_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_1 || ORIG_REF_NAME==bd_197a_auto_ss_slid_1} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_28/bd_197a_auto_ss_slid_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_2 || ORIG_REF_NAME==bd_197a_auto_ss_slid_2} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_29/bd_197a_auto_ss_slid_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_3 || ORIG_REF_NAME==bd_197a_auto_ss_slid_3} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_30/bd_197a_auto_ss_slid_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_4 || ORIG_REF_NAME==bd_197a_auto_ss_slid_4} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_31/bd_197a_auto_ss_slid_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slid_5 || ORIG_REF_NAME==bd_197a_auto_ss_slid_5} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_13/bd_197a_m00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m00_regslice_0 || ORIG_REF_NAME==bd_197a_m00_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_14/bd_197a_m01_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m01_regslice_0 || ORIG_REF_NAME==bd_197a_m01_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_21/bd_197a_auto_ss_slidr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_0 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_15/bd_197a_m02_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m02_regslice_0 || ORIG_REF_NAME==bd_197a_m02_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_22/bd_197a_auto_ss_slidr_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_1 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_1} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_16/bd_197a_m04_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m04_regslice_0 || ORIG_REF_NAME==bd_197a_m04_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_23/bd_197a_auto_ss_slidr_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_2 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_2} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_17/bd_197a_m05_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m05_regslice_0 || ORIG_REF_NAME==bd_197a_m05_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_24/bd_197a_auto_ss_slidr_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_3 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_3} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_18/bd_197a_m06_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m06_regslice_0 || ORIG_REF_NAME==bd_197a_m06_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_19/bd_197a_m07_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m07_regslice_0 || ORIG_REF_NAME==bd_197a_m07_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_20/bd_197a_m08_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_m08_regslice_0 || ORIG_REF_NAME==bd_197a_m08_regslice_0} -quiet] -quiet

# IP: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_25/bd_197a_auto_ss_slidr_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_197a_auto_ss_slidr_4 || ORIG_REF_NAME==bd_197a_auto_ss_slidr_4} -quiet] -quiet

# XDC: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/bd_197a_ooc.xdc

# XDC: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/design_1_v_proc_ss_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
