# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_25/bd_197a_auto_ss_slidr_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_197a_auto_ss_slidr_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/Vivado/CPRE488_git/cpre488-mp2/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_25/bd_197a_auto_ss_slidr_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_197a_auto_ss_slidr_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
