/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JKMouseScroll
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  scrollSpeed: 50
};
var JKMouseScroll = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.lastGPress = 0;
    this.handleKeyPress = (event) => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!activeView || activeView.getMode() !== "preview")
        return;
      const previewContent = activeView.previewMode.containerEl.querySelector(".markdown-preview-view");
      if (!previewContent)
        return;
      const now = Date.now();
      const speed = this.settings.scrollSpeed;
      switch (event.key) {
        case "g":
          if (!event.shiftKey) {
            if (now - this.lastGPress < 500) {
              previewContent.scrollTo({ top: 0, behavior: "smooth" });
              event.preventDefault();
            }
            this.lastGPress = now;
          }
          break;
        case "G":
          if (event.shiftKey) {
            previewContent.scrollTo({
              top: previewContent.scrollHeight,
              behavior: "smooth"
            });
            event.preventDefault();
          }
          break;
        case "j":
          previewContent.scrollBy({ top: speed, behavior: "smooth" });
          event.preventDefault();
          break;
        case "k":
          previewContent.scrollBy({ top: -speed, behavior: "smooth" });
          event.preventDefault();
          break;
      }
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new JKMouseScrollSettingTab(this.app, this));
    this.registerDomEvent(document, "keydown", this.handleKeyPress);
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = { ...DEFAULT_SETTINGS, ...await this.loadData() };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var JKMouseScrollSettingTab = class extends import_obsidian.PluginSettingTab {
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Scroll speed").setDesc("Pixels to scroll per keypress (default: 50)").addText((text) => text.setPlaceholder("50").setValue(this.plugin.settings.scrollSpeed.toString()).onChange(async (value) => {
      this.plugin.settings.scrollSpeed = parseInt(value) || 50;
      await this.plugin.saveSettings();
    }));
  }
};


/* nosourcemap */